---
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
image: gitpod/workspace-java-17
tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - richardwillis.vscode-gradle
    - vscjava.vscode-spring-boot-dashboard
    - Pivotal.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-test
