version: '3.1'
services:

  catalogservice:
    build: ../
    container_name: catalogservice
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres:latest
    container_name: catalogservice_postgresqldb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
