version: '3.8'
services:

  postgresqldb:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=appUser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
