version: '3.8'
services:

  postgresqldb:
    image: postgres:latest
    container_name: postgres-order-service
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"

